### ISSUE TITLE
Szoftverkövetelmények kiírása

### ISSUE THREAD

**Issue by ZoltanMaradics** [ZoltanMaradics/Elosztott#1]
Szoftverkövetelmények dokumentáció elkészítése

**Comment by GalEnikoLili** [comment]
[elosztott_specifikacio.docx](https://github.com/ZoltanMaradics/Elosztott/files/466158/elosztott_specifikacio.docx)

**Comment by ZoltanMaradics** [comment]
A dokumentáció alapján készíts Wiki oldalt

**Comment by GalEnikoLili** [comment]
Végeztem

**Comment by ZoltanMaradics** [comment]
Review-va
